version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: mysql-container
    restart: always
    platform: linux/arm64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${DB_PASSWORD} --silent"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
      
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-network
    platform: linux/arm64

  metabase:
    image: metabase/metabase:v0.52.3
    container_name: metabase-container
    restart: always
    platform: linux/amd64
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/metabase.db
    environment:
      JAVA_TIMEZONE: ${MB_JAVA_TIMEZONE}
    ports:
      - "3000:3000"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
