-- Generated by build_enrollment_inserts.py (CanvasID from filename)
SET NAMES utf8mb4;
USE `Micro-Surveys`;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196015, '2641084', 'Student'),
  (196015, '2697363', 'Student'),
  (196015, '2651146', 'Student'),
  (196015, '2717128', 'Student'),
  (196015, '2709072', 'Student'),
  (196015, '2691644', 'Student'),
  (196015, '2669621', 'Student'),
  (196015, '2716907', 'Student'),
  (196015, '2621790', 'Student'),
  (196015, '2709663', 'Student'),
  (196015, '2713985', 'Student'),
  (196015, '2739768', 'Student'),
  (196015, '2549408', 'Student'),
  (196015, '2614690', 'Student'),
  (196015, '0165441', 'Teacher'),
  (196015, '2716131', 'Student'),
  (196015, '2679364', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196016, '2720405', 'Student'),
  (196016, '2641084', 'Student'),
  (196016, '2697363', 'Student'),
  (196016, '2682893', 'Student'),
  (196016, '2613498', 'Student'),
  (196016, '2651146', 'Student'),
  (196016, '2676986', 'Student'),
  (196016, '2717128', 'Student'),
  (196016, '2709072', 'Student'),
  (196016, '2691644', 'Student'),
  (196016, '2645687', 'Student'),
  (196016, '2716907', 'Student'),
  (196016, '2675385', 'Student'),
  (196016, '2666426', 'Student'),
  (196016, '2709663', 'Student'),
  (196016, '2713985', 'Student'),
  (196016, '2648017', 'Student'),
  (196016, '2739768', 'Student'),
  (196016, '2680236', 'Student'),
  (196016, '0165441', 'Teacher'),
  (196016, '2716131', 'Student'),
  (196016, '2679364', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196017, '2668220', 'Student'),
  (196017, '2676986', 'Student'),
  (196017, '2510344', 'Teacher'),
  (196017, '2680237', 'Student'),
  (196017, '2649597', 'Student'),
  (196017, '2641047', 'Student'),
  (196017, '2680206', 'Student'),
  (196017, '2644576', 'Student'),
  (196017, '2621790', 'Student'),
  (196017, '2632828', 'Student'),
  (196017, '2679697', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196018, '2694320', 'Student'),
  (196018, '2613138', 'Student'),
  (196018, '2666335', 'Student'),
  (196018, '2682893', 'Student'),
  (196018, '2668220', 'Student'),
  (196018, '2675385', 'Student'),
  (196018, '2671187', 'Student'),
  (196018, '2679916', 'Teacher'),
  (196018, '2713985', 'Student'),
  (196018, '2714369', 'Student'),
  (196018, '2648017', 'Student'),
  (196018, '2679697', 'Student'),
  (196018, '2660717', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196019, '2697363', 'Student'),
  (196019, '2736262', 'Student'),
  (196019, '2718911', 'Student'),
  (196019, '2720444', 'Student'),
  (196019, '2651146', 'Student'),
  (196019, '2729820', 'Student'),
  (196019, '2725680', 'Student'),
  (196019, '2711051', 'Student'),
  (196019, '2692253', 'Student'),
  (196019, '2717103', 'Student'),
  (196019, '2716590', 'Student'),
  (196019, '2693116', 'Student'),
  (196019, '2716907', 'Student'),
  (196019, '2716255', 'Student'),
  (196019, '2436103', 'Teacher'),
  (196019, '2656078', 'Student'),
  (196019, '2646497', 'Student'),
  (196019, '2739768', 'Student'),
  (196019, '2727144', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196020, '2718827', 'Student'),
  (196020, '2726254', 'Student'),
  (196020, '2403515', 'Teacher'),
  (196020, '2719887', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196021, '2718827', 'Student'),
  (196021, '2156734', 'Teacher'),
  (196021, '2726254', 'Student'),
  (196021, '2719887', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196023, '2736262', 'Student'),
  (196023, '2718911', 'Student'),
  (196023, '2720444', 'Student'),
  (196023, '2725680', 'Student'),
  (196023, '2711051', 'Student'),
  (196023, '2692253', 'Student'),
  (196023, '2709072', 'Student'),
  (196023, '2717103', 'Student'),
  (196023, '2716590', 'Student'),
  (196023, '2693116', 'Student'),
  (196023, '2669621', 'Student'),
  (196023, '2694778', 'Student'),
  (196023, '2716907', 'Student'),
  (196023, '2716255', 'Student'),
  (196023, '2656078', 'Student'),
  (196023, '2646497', 'Student'),
  (196023, '2714369', 'Student'),
  (196023, '2582625', 'Teacher'),
  (196023, '2679364', 'Student'),
  (196023, '2727144', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196024, '2718827', 'Student'),
  (196024, '2508344', 'Teacher'),
  (196024, '2726254', 'Student'),
  (196024, '2719887', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196025, '2613138', 'Student'),
  (196025, '2682893', 'Student'),
  (196025, '2675757', 'Student'),
  (196025, '2669622', 'Student'),
  (196025, '2691644', 'Student'),
  (196025, '1798701', 'Teacher'),
  (196025, '2680237', 'Student'),
  (196025, '2675385', 'Student'),
  (196025, '2666426', 'Student'),
  (196025, '2646097', 'Student'),
  (196025, '2644576', 'Student'),
  (196025, '2605800', 'Student'),
  (196025, '2677981', 'Student'),
  (196025, '2709663', 'Student'),
  (196025, '2648017', 'Student'),
  (196025, '2680236', 'Student'),
  (196025, '2660717', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (196026, '2694320', 'Student'),
  (196026, '2729820', 'Student'),
  (196026, '2531665', 'Teacher'),
  (196026, '2717128', 'Student'),
  (196026, '2717103', 'Student'),
  (196026, '2694778', 'Student'),
  (196026, '2716255', 'Student'),
  (196026, '2671187', 'Student'),
  (196026, '2716428', 'Student'),
  (196026, '2716131', 'Student'),
  (196026, '2679364', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (197865, '2628629', 'Teacher'),
  (197865, '2697363', 'Student'),
  (197865, '2736262', 'Student'),
  (197865, '2729820', 'Student'),
  (197865, '2725680', 'Student'),
  (197865, '2692253', 'Student'),
  (197865, '2693116', 'Student'),
  (197865, '2739768', 'Student'),
  (197865, '2727144', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (197981, '2694320', 'Student'),
  (197981, '2736262', 'Student'),
  (197981, '2718911', 'Student'),
  (197981, '2720444', 'Student'),
  (197981, '2669622', 'Student'),
  (197981, '2729820', 'Student'),
  (197981, '2725680', 'Student'),
  (197981, '2711051', 'Student'),
  (197981, '2692253', 'Student'),
  (197981, '2717103', 'Student'),
  (197981, '2680237', 'Student'),
  (197981, '2693116', 'Student'),
  (197981, '2694778', 'Student'),
  (197981, '2716255', 'Student'),
  (197981, '2671187', 'Student'),
  (197981, '2382668', 'Teacher'),
  (197981, '2656078', 'Student'),
  (197981, '2646497', 'Student'),
  (197981, '2716428', 'Student'),
  (197981, '2727144', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;

INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)
VALUES
  (199940, '2718827', 'Student'),
  (199940, '2735545', 'Teacher'),
  (199940, '2726254', 'Student'),
  (199940, '2719887', 'Student')
ON DUPLICATE KEY UPDATE Empl_ID = Empl_ID;
