-- Generated by build_survey_responses_inserts.py
SET NAMES utf8mb4;
USE `Micro-Surveys`;

INSERT INTO `Survey_Responses` (Response_ID, Survey_ID, IPAddress, Progress, Duration, Finished, RecordedDate, LocationLatitude, LocationLongitude, UserLanguage, CanvasID, Created_At)
VALUES
  ('R_9DhZRPpo40jGnCC', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-01-29 20:59:57', NULL, NULL, 'EN', 196016, '2026-01-29 20:59:57'),
  ('R_9bwOaj54MfSKKbv', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-01-31 03:16:04', NULL, NULL, 'EN', 196015, '2026-01-31 03:16:03'),
  ('R_4K38zbszB0MpXNU', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-05 01:21:21', NULL, NULL, 'EN', 196019, '2026-02-05 01:21:21'),
  ('R_9EKh5qXcRpkJrGM', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-05 04:34:55', NULL, NULL, 'EN', 196016, '2026-02-05 04:34:54'),
  ('R_9EihKcZpHiYZo5w', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-05 04:35:12', NULL, NULL, 'EN', 196015, '2026-02-05 04:35:12'),
  ('R_9FRU8fUNHQvXeux', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-05 04:35:43', NULL, NULL, 'EN', 196025, '2026-02-05 04:35:43'),
  ('R_9Xwq6MAFhIqH2sV', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-07 07:58:11', NULL, NULL, 'EN', 196026, '2026-02-07 07:58:11'),
  ('R_9kQ3Vki329zdSBr', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-07 07:58:32', NULL, NULL, 'EN', 197981, '2026-02-07 07:58:32'),
  ('R_9bG5RQRpK0LcY4p', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-07 07:58:56', NULL, NULL, 'EN', 196023, '2026-02-07 07:58:55'),
  ('R_4EQJoGqEheibWdv', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-08 04:29:22', NULL, NULL, 'EN', 196016, '2026-02-08 04:29:21'),
  ('R_4EyuKDgX6ZebGJF', 'ERAU_ASIA', '*******', 100, NULL, 1, '2026-02-09 04:27:53', NULL, NULL, 'EN', 196015, '2026-02-09 04:27:52')
ON DUPLICATE KEY UPDATE Response_ID = Response_ID;
