#!/usr/bin/env python3
"""
Generate MySQL INSERTs into People from Canvas roster CSVs.

Expected column order (Canvas People-page export):
  0 Profile Picture | 1 Name | 2 Login ID | 3 SIS ID | 4 Section | 5 Role | ...

Usage:
  python3 4-build_people_inserts_positional.py --root Enrollment --outfile people_inserts.sql
  python3 4-build_people_inserts_positional.py --root Enrollment --stdout > people_inserts.sql
"""

import sys
from pathlib import Path
import argparse
from typing import Dict, List, Optional

from pipeline import discover_roster_csvs, parse_roster_path, esc


def log(msg: str, verbose: bool) -> None:
    if verbose:
        print(msg)


def batch_insert_values(rows: List[Dict], batch_size: int = 500) -> List[str]:
    stmts: List[str] = []
    for i in range(0, len(rows), batch_size):
        chunk = rows[i:i + batch_size]
        values_sql = [
            f"({esc(r['name'])}, {esc(r['login'])}, {esc(r['empl'])}, {esc(r['role'])})"
            for r in chunk
        ]
        stmt = (
            "INSERT INTO `People` (Name, Login_ID, EMPL_ID, Role)\nVALUES\n  "
            + ",\n  ".join(values_sql)
            + "\nON DUPLICATE KEY UPDATE Name=VALUES(Name), Login_ID=VALUES(Login_ID), Role=VALUES(Role);"
        )
        stmts.append(stmt)
    return stmts


def build_sql(all_rows: List[Dict], dbname: Optional[str],
              emit_use: bool, batch: int) -> str:
    header = [
        "-- Generated by 4-build_people_inserts_positional.py",
        "SET NAMES utf8mb4;",
    ]
    if emit_use and dbname:
        header.append(f"USE `{dbname}`;")
    header.append("")
    inserts = batch_insert_values(all_rows, batch_size=batch)
    return "\n".join(header + inserts) + ("\n" if inserts else "")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate MySQL INSERTs for People from Canvas roster CSVs.")
    ap.add_argument("--root",    default=".", help="Directory to scan for roster CSVs")
    ap.add_argument("--outfile", default="people_inserts.sql", help="Output .sql file path")
    ap.add_argument("--stdout",  action="store_true", help="Write SQL to stdout instead of file")
    ap.add_argument("--dbname",  default="Micro-Surveys", help="DB name for USE `<db>`;")
    ap.add_argument("--no-use",  action="store_true", help="Do not emit USE `<db>`;")
    ap.add_argument("--batch",   type=int, default=500, help="Rows per INSERT batch")
    ap.add_argument("--verbose", action="store_true", help="Verbose logging")
    args = ap.parse_args(argv)

    root = Path(args.root).expanduser().resolve()
    csvs = discover_roster_csvs(root)
    if not csvs:
        print("No CSV files found under:", root, file=sys.stderr)
        return 1

    log(f"Found {len(csvs)} CSV file(s) under {root}", args.verbose)

    all_rows: List[Dict] = []
    for p in csvs:
        rows = parse_roster_path(p)
        if not rows:
            log(f"⚠ Skipping non-roster CSV: {p.name}", args.verbose)
            continue
        log(f"✔ {p.name}: {len(rows)} valid row(s)", args.verbose)
        all_rows.extend(rows)

    if not all_rows:
        print("No valid rows found (need roster CSVs with Name/Login ID/SIS ID/Role columns).",
              file=sys.stderr)
        return 2

    log(f"🧮 Total rows to emit: {len(all_rows)}", args.verbose)

    sql_text = build_sql(
        all_rows=all_rows,
        dbname=args.dbname,
        emit_use=not args.no_use,
        batch=args.batch,
    )

    if args.stdout:
        print(sql_text, end="")
    else:
        outpath = Path(args.outfile).expanduser().resolve()
        outpath.parent.mkdir(parents=True, exist_ok=True)
        with outpath.open("w", encoding="utf-8") as f:
            f.write(sql_text)
        print(f"✅ Wrote {len(all_rows)} rows to {outpath}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
