#!/usr/bin/env python3
"""
Generate SQL INSERT statements for the Enrollment table
from Canvas roster CSVs. The Canvas course ID is taken from the filename.

Filename convention:
  Enrollment/196025.csv            → CanvasID 196025
  Enrollment/course_roster_196025.csv → CanvasID 196025

Usage:
  python3 5-build_enrollment_inserts.py --root Enrollment --outfile enrollment_inserts.sql
  python3 5-build_enrollment_inserts.py --root Enrollment --stdout > enrollment_inserts.sql
"""

import sys
from pathlib import Path
import argparse
from typing import Dict, List, Optional

from pipeline import canvas_id_from_filename, discover_roster_csvs, parse_roster_path, esc


def log(msg: str, verbose: bool) -> None:
    if verbose:
        print(msg)


def build_course_sql(canvas_id: int, rows: List[Dict],
                     batch_size: int = 500) -> List[str]:
    stmts: List[str] = [f"DELETE FROM `Enrollment` WHERE CanvasID = {canvas_id};"]
    for i in range(0, len(rows), batch_size):
        chunk = rows[i:i + batch_size]
        values_sql = [
            f"({canvas_id}, {esc(r['empl'])}, {esc(r['role'])})"
            for r in chunk
        ]
        stmt = (
            "INSERT INTO `Enrollment` (CanvasID, Empl_ID, Role)\nVALUES\n  "
            + ",\n  ".join(values_sql)
            + ";"
        )
        stmts.append(stmt)
    return stmts


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate Enrollment INSERT SQL from Canvas roster CSVs.")
    ap.add_argument("--root",    default=".", help="Directory to scan for roster CSVs")
    ap.add_argument("--outfile", default="enrollment_inserts.sql", help="Output .sql file")
    ap.add_argument("--stdout",  action="store_true", help="Print SQL to stdout instead of writing file")
    ap.add_argument("--dbname",  default="Micro-Surveys", help="DB name for USE `<db>`;")
    ap.add_argument("--no-use",  action="store_true", help="Do not emit USE `<db>`;")
    ap.add_argument("--batch",   type=int, default=500, help="Rows per INSERT batch")
    ap.add_argument("--verbose", action="store_true", help="Verbose logging")
    args = ap.parse_args()

    root     = Path(args.root).expanduser().resolve()
    csv_files = discover_roster_csvs(root)
    if not csv_files:
        print("No CSV files found under:", root, file=sys.stderr)
        return 1

    sql_lines: List[str] = [
        "-- Generated by 5-build_enrollment_inserts.py",
        "SET NAMES utf8mb4;",
    ]
    if not args.no_use and args.dbname:
        sql_lines.append(f"USE `{args.dbname}`;")
    sql_lines.append("")

    emitted_courses = 0
    emitted_rows    = 0

    for csv_path in csv_files:
        canvas_id = canvas_id_from_filename(csv_path.name)
        if canvas_id is None:
            log(f"⚠ Skipping CSV with no CanvasID in filename: {csv_path.name}", args.verbose)
            continue

        rows = parse_roster_path(csv_path)
        if not rows:
            log(f"⚠ No valid roster rows in {csv_path.name}.", args.verbose)
            continue

        sql_lines.extend(build_course_sql(canvas_id, rows, batch_size=args.batch))
        sql_lines.append("")
        emitted_courses += 1
        emitted_rows    += len(rows)
        log(f"✔ {csv_path.name}: CanvasID={canvas_id}, rows={len(rows)}", args.verbose)

    if emitted_rows == 0:
        print("No enrollment rows emitted. Check roster filenames and CSV header format.",
              file=sys.stderr)
        return 2

    sql_text = "\n".join(sql_lines)
    if args.stdout:
        print(sql_text)
    else:
        outpath = Path(args.outfile).expanduser().resolve()
        outpath.parent.mkdir(parents=True, exist_ok=True)
        outpath.write_text(sql_text, encoding="utf-8")
        print(f"✅ Wrote {emitted_rows} enrollment rows across "
              f"{emitted_courses} course roster file(s) to {outpath}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
